import sys
import time

def print_header(algo_name):
    """Prints the algorithm header."""
    header = f"{algo_name} PAGE REPLACEMENT ALGORITHM"
    print(f"\n\t{header}")
    print(f"\t{'=' * len(header)}\n")

def display_frames(frames):
    """Prints the current state of memory frames."""
    for i, val in enumerate(frames):
        # Display 0 if the frame is empty (None), otherwise the page value
        display_val = val if val is not None else 0
        print(f"    {i}[{display_val}]")
    print()

def get_optimal_victim(frames, ref_list, current_idx):
    """
    Finds the index of the victim page for OPTIMAL algorithm.
    """
    farthest_idx = -1
    victim_idx = -1
    
    for i in range(len(frames)):
        page = frames[i]
        try:
            next_use = ref_list[current_idx+1:].index(page)
        except ValueError:
            return i
        
        if next_use > farthest_idx:
            farthest_idx = next_use
            victim_idx = i
            
    return victim_idx

def get_lru_victim(frames, ref_list, current_idx):
    """
    Finds the index of the victim page for LRU algorithm.
    """
    lru_time = current_idx
    victim_idx = -1
    
    for i in range(len(frames)):
        page = frames[i]
        last_used = -1
        for j in range(current_idx - 1, -1, -1):
            if ref_list[j] == page:
                last_used = j
                break
        
        if last_used < lru_time:
            lru_time = last_used
            victim_idx = i
            
    return victim_idx

def run_simulation(ref_string, size, algo_option):
    ref_list = list(ref_string)
    frames = [None] * size
    
    algo_name = ""
    if algo_option == 1: algo_name = "OPTIMAL"
    elif algo_option == 2: algo_name = "LRU"
    elif algo_option == 3: algo_name = "FIFO"
    
    print_header(algo_name)
    
    page_faults = 0
    fifo_ptr = 0 
    
    for i, page in enumerate(ref_list):
        # Pause for 1 second before processing next step
        time.sleep(1.0)
        
        status_msg = ""
        
        if page not in frames:
            if None in frames:
                empty_idx = frames.index(None)
                frames[empty_idx] = page
            else:
                status_msg = "   => Page Fault!"
                page_faults += 1
                
                victim = -1
                if algo_option == 1: # OPTIMAL
                    victim = get_optimal_victim(frames, ref_list, i)
                elif algo_option == 2: # LRU
                    victim = get_lru_victim(frames, ref_list, i)
                elif algo_option == 3: # FIFO
                    victim = fifo_ptr
                    fifo_ptr = (fifo_ptr + 1) % size
                
                frames[victim] = page
        
        print(f"Reference string: {page}{status_msg}")
        display_frames(frames)

    # Check page faults count for final message
    if page_faults == 0:
        print(f"  No Page Faults are generated by the {algo_name} algorithm!")
    else:
        print(f"  Total {page_faults} Page Fault(s) generated by the {algo_name} algorithm!")

def get_user_inputs():
    try:
        r_str = input("Enter a Page reference string without space <Max 20>: ").strip()
        f_size = int(input("Enter the size of Memory frame <Max 10>: "))
        return r_str, f_size
    except ValueError:
        print("Invalid input format.")
        return None, None

def main():
    print("\n\n\tPAGE REPLACEMENT ALGORITHM SIMULATION")
    print("\t=====================================\n")
    
    ref_string, frame_size = get_user_inputs()
    if ref_string is None: return

    while True:
        print("\n\tAlgorithm Option Menu:")
        print("\t======================")
        print("\t1. OPTIMAL  2. LRU")
        print("\t3. FIFO     4. Exit\n")
        
        choice = input("Select an OPTION from above by entering its number: ").strip()
        
        if choice == '4':
            break
        
        if choice in ['1', '2', '3']:
            run_simulation(ref_string, frame_size, int(choice))
            
            cont = input("\nEnter Y to continue or press any other key to Exit: ").strip().lower()
            if cont != 'y':
                break
            
            reuse = input("Enter N to use the same Page Reference and Memory Frame or press any key: ").strip().lower()
            if reuse != 'n':
                print("\n\tPAGE REPLACEMENT ALGORITHM SIMULATION")
                print("\t=====================================\n")
                ref_string, frame_size = get_user_inputs()
                if ref_string is None: break
        else:
            print("Invalid Option. Please select 1-4.")

if __name__ == "__main__":
    main()
